export const categories = ["Все", "Техника", "Мода", "Музыка", "Спорт", "Фото", "Книги", "Искусство"];

export const sampleItems = [
  {
    id: "demo-1",
    title: "Sony WH-1000XM5",
    category: "Аудио",
    image: "/demo/items/sony.png",
    wanted: "Механическая клавиатура",
    city: "Москва",
    likes: 47,
    trending: true,
  },
  {
    id: "demo-2",
    title: "Canon AE-1",
    category: "Фото",
    image: "/demo/items/canon.png",
    wanted: "Винтажные часы",
    city: "Москва",
    likes: 33,
  },
  {
    id: "demo-3",
    title: "Консультация по интерьеру",
    category: "Дизайн и интерьер",
    image: "/demo/items/interior.png",
    wanted: "Фотосъёмка, Книги по дизайну",
    city: "СПб",
    likes: 61,
    trending: true,
  },
  {
    id: "demo-4",
    title: "Коллекция винила",
    category: "Винил и носители",
    image: "/demo/items/vinyl.png",
    wanted: "Проигрыватель, Аудиотехника",
    city: "Санкт-Петербург",
    likes: 74,
  },
  {
    id: "demo-5",
    title: "Плёночная фотосъёмка",
    category: "Фото и видео",
    image: "/demo/items/canon.png",
    wanted: "Винил, Книги по фотографии",
    city: "Санкт-Петербург",
    likes: 51,
  },
  {
    id: "demo-6",
    title: "Подбор аудиосистемы",
    category: "Аудио",
    image: "/demo/items/sony.png",
    wanted: "Консультация по интерьеру",
    city: "Москва",
    likes: 64,
    trending: true,
  },
];
