export const categories = ["Все", "Техника", "Мода", "Музыка", "Спорт", "Фото", "Книги", "Искусство"];

export const sampleItems = [
  {
    id: "demo-1",
    title: "Sony WH-1000XM5",
    category: "Аудио",
    image: "/demo/items/sony.jpg",
    wanted: "Механическая клавиатура",
    city: "Москва",
    likes: 47,
    trending: true,
  },
  {
    id: "demo-2",
    title: "Canon AE-1",
    category: "Фото",
    image: "/demo/items/canon.jpg",
    wanted: "Винтажные часы",
    city: "Москва",
    likes: 33,
  },
  {
    id: "demo-3",
    title: "Nike Air Jordan",
    category: "Мода",
    image: "/demo/items/canon.jpg",
    wanted: "Дизайнерская сумка",
    city: "СПб",
    likes: 61,
    trending: true,
  },
  {
    id: "demo-4",
    title: "MacBook Pro M3",
    category: "Техника",
    image: "/demo/items/sony.jpg",
    wanted: "iPad Pro",
    city: "Казань",
    likes: 74,
  },
  {
    id: "demo-5",
    title: "Vinyl Records Collection",
    category: "Музыка",
    image: "/demo/items/vinyl.jpg",
    wanted: "Проигрыватель",
    city: "Москва",
    likes: 51,
  },
  {
    id: "demo-6",
    title: "Apple Watch Series 9",
    category: "Техника",
    image: "/demo/items/sony.jpg",
    wanted: "AirPods Pro",
    city: "Москва",
    likes: 64,
    trending: true,
  },
];
